
# Model v0.2 - Trends Shifted By Store Number

```{r, message=FALSE}
library(dplyr)
library(tsibble)
library(feasts)
library(stringr)
library(lubridate)
library(readr)
library(tidyr)
library(ggplot2)

DATA_DIR = paste0(Sys.getenv("DATA_DIR"), "/store-sales-time-series")

TRAIN_PATH = paste0(DATA_DIR, "/train.csv")
TEST_PATH = paste0(DATA_DIR, "/test.csv")

# give ourselves 3 months worth of holdout data
training_end_date = "2017-04-30"

# load training dataset
df = read_csv(TRAIN_PATH) %>% 
  tsibble(
    key = c(store_nbr, family),
    index = date
  )

df_test = read_csv(TEST_PATH) %>% 
  tsibble(
    key = c(store_nbr, family),
    index = date
  )
```

# Prepare Data

```{r}
df_holdout <- df %>% 
  filter(
    date > training_end_date
  )

df_train <- df %>% 
  filter(
    date <= training_end_date
  )

cutoff_dates <- c(
  "AUTOMOTIVE" = "2013-01-01",
  "BABY CARE" = "2016-01-01",
  "BEAUTY" = "2013-01-01",
  "BEVERAGES" = "2015-06-01",
  "BOOKS" = "2016-10-12",
  "BREAD/BAKERY" = "2013-01-01",
  "CELEBRATION" = "2016-01-01",
  "CLEANING" = "2013-01-01",
  "DAIRY" = "2014-01-01",
  "DELI" = "2013-01-01",
  "EGGS" = "2013-01-01",
  "FROZEN FOODS" = "2013-01-01",
  "GROCERY I" = "2013-01-01",
  "GROCERY II" = "2013-01-01",
  "HARDWARE" = "2013-01-01",
  "HOME AND KITCHEN I" = "2015-01-01",
  "HOME AND KITCHEN II" = "2015-06-01",
  "HOME APPLIANCES" = "2013-01-01",
  "HOME CARE" = "2015-06-01",
  "LADIESWEAR" = "2015-06-01",
  "LAWN AND GARDEN" = "2016-12-01",
  "LINGERIE" = "2013-01-01",
  "LIQUOR,WINE,BEER" = "2013-01-01",
  "MAGAZINES" = "2016-01-01",
  "MEATS" = "2013-01-01",
  "PERSONAL CARE" = "2013-01-01",
  "PET SUPPLIES" = "2015-06-01",
  "PLAYERS AND ELECTRONICS" = "2015-06-01",
  "POULTRY" = "2014-01-01",
  "PREPARED FOODS" = "2013-01-01",
  "PRODUCE" = "2015-06-01",
  "SCHOOL AND OFFICE SUPPLIES" = "2015-06-01",
  "SEAFOOD" = "2014-01-01"
)

family_cutoff_dates <- tibble(
  family = names(cutoff_dates),
  family_cutoff_date = cutoff_dates
)

df_train <- df_train %>% 
  filter(
    date >= "2016-01-01"
  ) %>% 
  left_join(
    family_cutoff_dates,
    by = "family"
  ) %>% 
  filter(
    date > family_cutoff_date
  ) %>% 
  mutate(
    log_sales = log(0.1 + sales)
  )
```

```{r}
df_train
```



# Model

```{r}
model <- lm(
  log_sales ~ family + family:date + as.factor(store_nbr) - 1,
  data = df_train
)

summary(model)
```

```{r}
results_data <- df_holdout

results_data$prediction <- exp(predict(model, df_holdout)) - 0.1

results_data <- results_data %>% 
  mutate(
    residual = sales - prediction,
    log_adj_residuals = log(1 + sales) - log(1 + prediction)
  )

results_data %>% 
  as_tibble() %>% 
  summarise(
    rmse = sqrt( mean(residual^2) ),
    rmsle = sqrt( mean(log_adj_residuals^2) )
  )

results_data %>% 
  as_tibble() %>% 
  ggplot(aes(date, residual)) + 
  geom_point()
```








